name: Run pull-request syntax workflows
on:
- pull_request
jobs:
  pre_commit:
    uses: figment-networks/figment-github-actions/.github/workflows/pre-commit.yaml@89b46e3bd29417a8c1a9129f0a200f63bf98b7e2
    with:
      python_version: ${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        python_version:
        - "3.10"
        - "3.11"
        - "3.12"
